language: node_js
node_js: lts/*

services:
  - docker

env:
  - NODE_VERSION=8
  - NODE_VERSION=10
  - NODE_VERSION=12

script:
  - docker-compose run -T test

install:
  - bash scripts/build-docker.sh

cache:
  directories:
    - /tmp/.docker-images

before_install:
  - docker load -i /tmp/.docker-images || true
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - docker-compose up -d kafka zookeeper
  - npm i -g coveralls

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - cat coverage/lcov.info | coveralls

after_script:
  - docker-compose down -v

before_cache:
  - docker save -o /tmp/.docker-images $(docker images -a -q)
