language: node_js
dist: xenial

node_js:
  - '8'
  - '10'
  - '12'


cache:
  directories:
    - 'node_modules'

script:
  - pnpm run test:coverage

install:
  - pnpm recursive install --frozen-lockfile

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm add -g typescript
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - pnpm run coveralls
